
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHUBHAM
 */
public class buy extends javax.swing.JFrame {

    /**
     * Creates new form buy
     */
   public buy()
   {
       initComponents();
       
   }
     public buy(int a,String b)
   {
       initComponents();
       tt.setText(""+a);
       nameee.setText(b);
       
   }
      public buy(int g)
   {
       initComponents();
       tt.setText(""+g);
      
       
   }
     
  
         
     
    

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        CO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        tc = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        nameee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/E kart logo.jpeg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 120));

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 780, 10));

        jPanel13.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 157, 780, -1));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 120));

        name.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 350, 30));

        CO.setBackground(new java.awt.Color(255, 102, 51));
        CO.setText("PROCEED");
        CO.setEnabled(false);
        CO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COActionPerformed(evt);
            }
        });
        getContentPane().add(CO, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 160, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL BILL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTER NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, -1));

        tt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 350, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ENTER DELIVERY ADDRESS::");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, -1));

        add.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 350, 30));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("1.)Item(s) will be delivered in 2-3 working \ndays.\n2.)Item(s) bought will be replaced within 10 \ndays of delivery.\n3.)Extra charge of Rs.40 will be charged for \ndelivery.\n4.)Delivery will not be charged by paying by \nekart paybalance or debit/credit card");
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder("TERMS & CONDITIONS"));
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 174, 370, 190));

        tc.setBackground(new java.awt.Color(255, 255, 255));
        tc.setText("I have accepted all the TERMS & CONDITION");
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        getContentPane().add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setText("Deliver to Registered Address");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel4.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 109, -1, -1));

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setText("Registerd Name");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel4.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 40, 109, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 780, 290));

        nameee.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        nameee.setText("sid");
        getContentPane().add(nameee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 380, 20));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 780, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void COActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COActionPerformed
        // TODO add your handling code here:
dispose();                String a= nameee.getText();
                int b= Integer.parseInt(tt.getText());

        String c = name.getText();
        String d = add.getText();
        
        new bill(a,b,c,d).setVisible(true);
        
 
 
       
       
    }//GEN-LAST:event_COActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
          dispose();
       new HOME1().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
        if(tc.isSelected()==true)
        CO.setEnabled(true);
        else
        CO.setEnabled(false);
    }//GEN-LAST:event_tcActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        
        if(c1.isSelected()==true)
        {
            try{
                Class.forName("java.sql.Driver");
                Connection  ccon = DriverManager.getConnection("jdbc:mysql://localhost/ekart","root","root");
                Statement  s = ccon.createStatement();
                String query = "Select  * from accounts where id ='"+nameee.getText()+"';";
                ResultSet rs = s.executeQuery(query);
                if(rs.next())
                {
                   add.setText(rs.getString(7));
                    
                }
                
                
            }catch(Exception error)
            {
                JOptionPane.showMessageDialog(this,"Connection error");
                        
            }
        }
        else
            
        {
            add.setText("");
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
            if(c2.isSelected()==true)
        {
            try{
                Class.forName("java.sql.Driver");
                Connection  ccon = DriverManager.getConnection("jdbc:mysql://localhost/ekart","root","root");
                Statement  s = ccon.createStatement();
                String query = "Select  * from accounts where id ='"+nameee.getText()+"';";
                ResultSet rs = s.executeQuery(query);
                if(rs.next())
                {
                   name.setText(rs.getString(3));
                    
                }
                
                
            }catch(Exception error)
            {
                JOptionPane.showMessageDialog(this,"Connection error");
                        
            }
        }
        else
            
        {
            name.setText("");
        }
    }//GEN-LAST:event_c2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CO;
    private javax.swing.JTextField add;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameee;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JCheckBox tc;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
